---
title: "CrimeData"
author: "Aeint Thet Ngon"
date: "June 10, 2017"
output: pdf_document
---

```{r,}
library(dplyr)
library(ggplot2)
library(reshape2)
library(plotly)
```

```{r}
setwd("C:/Users/Aeint Thet Ngon/Documents/Portfolio/Crime DC")

files=list.files(pattern="*.csv")
names=paste("X", 2008:2017, sep="")

dc=NULL

for (i in 1:length(files)){
  assign(names[i], read.csv(files[i]))
  dc <- rbind(dc,read.csv(files[i]))
}

chicago <- read.csv("C:/Users/Aeint Thet Ngon/Documents/Portfolio/Chicago Crimes_-_2008_to_present.csv")
```

```{r}
chicago <- chicago %>%
  mutate(DT=as.POSIXct(strptime(Date, "%m/%d/%Y %I:%M:%S %p"))) %>% 
  mutate(year=strftime(DT, "%Y"), hour=strftime(DT, "%H"), wday=weekdays(DT))

#chiTown_Y<- chicago %>% group_by(year) %>% mutate(arrested=mean(Arrest=='true')) %>% select(year, arrested) %>% distinct()

dc <- dc %>% mutate(DT=as.POSIXct(strptime(substring(REPORT_DAT, 1, 19), "%Y-%m-%dT%H:%M:%S"))) %>%
  mutate(year=strftime(DT, "%Y"), hour=strftime(DT, "%H"), wday=weekdays(DT))
```


```{r}
chi_l <- chicago %>% group_by(year, Primary.Type) %>% summarise(n=n())
dc_l <- dc %>% group_by(year, OFFENSE) %>% summarise(n=n())

g <- ggplot(chicago, aes(year))
g + geom_bar(aes(fill = Primary.Type))

gg <- ggplot(dc, aes(year))
gg + geom_bar(aes(fill = OFFENSE))

ggplot(data=chi_l, aes(x=year, y=n, group=Primary.Type, colour=Primary.Type)) +geom_line() +geom_point()

ggplot(data=dc_l, aes(x=year, y=n, group=OFFENSE, colour=OFFENSE)) +geom_line() +geom_point()


```


```{r}
arr_prop<- chicago %>% group_by(year) %>% mutate(arrested=mean(Arrest=='true')) %>% select(year, arrested) %>% distinct() %>% na.omit()
arr_prop
arr <- chicago %>% group_by(year, Primary.Type) %>% mutate(arrested=mean(Arrest=="true")) %>% select(year, Primary.Type, arrested) %>% distinct() %>% na.omit()
```

```{r}
dc1 <- dc %>% filter(year!= "2017") %>%group_by(year, hour) %>% summarise(n=n()) %>% arrange(year, hour) %>% transform(year=as.factor(year), hour=as.factor(hour))
chi <- chicago %>% filter(year!= "2017")%>% group_by(year, hour) %>% summarise(n=n()) %>% na.omit()

dc_mat <- acast(dc1, year~hour, value.var="n")
#dc_heatmap <- heatmap(dc_mat, Rowv=NA, Colv=NA, col = cm.colors(256), scale="column")

chi_mat <-acast(chi, year~hour, value.var="n")
#chi_mat
#chi_heatmap <- heatmap(chi_mat, Rowv=NA, Colv=NA, col = cm.colors(256), scale="column")

plot_ly(x=colnames(dc_mat), y=rownames(dc_mat), z=dc_mat, type="heatmap")

plot_ly(x=colnames(chi_mat), y=rownames(chi_mat), z=chi_mat, type="heatmap")

X2016 <- X2016 %>% mutate(DT=as.POSIXct(strptime(substring(REPORT_DAT, 1, 19), "%Y-%m-%dT%H:%M:%S"))) %>%
  mutate(year=strftime(DT, "%Y"), hour=strftime(DT, "%H"), wday=weekdays(DT))

X16 <- X2016 %>% group_by(OFFENSE, hour) %>% summarise(n=n())
X16_mat <- acast(X16, OFFENSE~hour, value.var="n")

plot_ly(x=colnames(X16_mat), y=rownames(X16_mat), z=X16_mat, type="heatmap")

```































